### ISSUE TITLE
PCD Study Jam 2

### ISSUE THREAD

**Issue by suhanacharya** [so-sc/open-design#19]
## Event Description:
Session to go through all the CPL Lab programs for 1st years, possible viva questions and Ace the test.
Link to war-room issue
https://github.com/so-sc/war-room/issues/19

#### Completion Date: 13/12/2019   😬😬
- [x] Create cover for Whatsapp media and website.

#### Details of the designs:
Design can be similar to the previous pcd study jam or different as you wish. 😄 
https://sosc.org.in/events/pcd-lab-study-jam-2019

**Comment by suhanacharya** [comment]
@dhanushp 😬 I know it's a bit rushed....

**Comment by nathanielmathew** [comment]
I'll do it if @dhanushp can't 👍

**Comment by nathanielmathew** [comment]
![PCD_STUDY_JAM](https://user-images.githubusercontent.com/22280173/70722281-ff6f5e80-1d1c-11ea-93ed-07616ad96ac1.png)
@suhanacharya

**Comment by suhanacharya** [comment]
Thanks mate 🔥  👍 That was quick! 😄 @nathanielmathew
