### ISSUE TITLE
Build Your Portfolio 

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/open-design#25]
## Event Description: 
_This Workshop is all about helping participants build their own portfolio_
_https://github.com/so-sc/war-room/issues/new?template=workshop.md_
#### Completion Date: 10/09/2020
Check all that is applicable, add new ones if needed, remove the lines which aren't required.
- [ ] Invitation cards (Mention the details of invitation)
- [x] SOSC Website Event Cover
- [ ] Poster (print)
- [x] Poster (Social Media)
- [ ] ID Cards (Mention what is required)
- [ ] Certificates (Mention the details below)
- [ ] Banner Outside Gate
- [ ] Others (Specify the details below)
#### Details of the designs:
Mozilla Logo , College Name and logo, MHRD logo required.

**Comment by dhanushp** [comment]
@rahul-nl Take care of this

**Comment by rahul-nl** [comment]
![MOZILLA POSTER](https://user-images.githubusercontent.com/45726796/92679378-e6481c80-f345-11ea-8d58-ee7b80436576.png)

**Comment by rahul-nl** [comment]
![Portfolio workshop](https://user-images.githubusercontent.com/45726796/92683962-f49c3580-f351-11ea-931c-da1ad87ad4a5.png)

**Comment by rahul-nl** [comment]
![MOZILLA POSTER](https://user-images.githubusercontent.com/45726796/92683999-041b7e80-f352-11ea-81dd-e771c25c5dae.png)

**Comment by rahul-nl** [comment]
![Asset 1](https://user-images.githubusercontent.com/45726796/92766636-04e4fc80-f3b4-11ea-8768-e81790c2dbdb.png)

**Comment by dhanushp** [comment]
Looks great! Thank you @rahul-nl
