### ISSUE TITLE
DevHost 2020 + Hacktoberfest 2020

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/open-design#26]
## Event Description:
_Try to explain what the event is about in detail_  
_Provide the link to the issue in war-room is the details are mentioned there_
#### Completion Date:
Check all that is applicable, add new ones if needed, remove the lines which aren't required.
- [ ] Poster (print)
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [x] Invitation cards (E-Invitation with Timeline of the event)
- [x] Certificates (Participant devhost:2020 , Participant HacktoberFest 2020 , Winner of Hackthon)
- [ ] Others (Specify the details below)
#### Details of the designs:
(Mention all the required details)

**Comment by dhanushp** [comment]
Not stale

**Comment by dhanushp** [comment]
@Basavarajeshwari-Ambi I have updated some of the files [here](https://github.com/so-sc/open-design/tree/master/devhost%202020).
Let me know if I have left anything out. 
Will add Devhost certificate soon.
