### ISSUE TITLE
Code_init() [30/01/2021]

### ISSUE THREAD

**Issue by akashdeepb** [so-sc/open-design#36]
## Event Description:
https://github.com/so-sc/war-room/issues/13
#### Completion Date: 26/01/2021
Check all that is applicaple, add new ones if needed, remove the lines which aren't required.
- [ ] Poster (print)
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [ ] Invitation cards (Mention the details of invitation)
- [ ] Certificates (Mention the details below)
- [ ] Others (Specify the details below)
#### Details of the designs:
Code _init_() will be name of the event, since it's focused more on people with 0 coding knowledge, try to make it appealing for these people.

**Comment by dhanushp** [comment]
![Web](https://user-images.githubusercontent.com/43709470/105639078-35798e80-5e9c-11eb-92ab-2f863dd762e5.png)

**Comment by dhanushp** [comment]
![Poster](https://user-images.githubusercontent.com/43709470/105812802-d79c9200-5fd4-11eb-9c27-fbc24b483c04.png)


Poster for the event @akashdeepb

**Comment by dhanushp** [comment]
Do let me know if any changes are required

**Comment by akashdeepb** [comment]
Looks really cool, there might be updates about venue

**Comment by dhanushp** [comment]
What's the updated date, time and venue? @akashdeepb

**Comment by akashdeepb** [comment]
Update it to Ground Floor Seminar hall and time 1:30 pm

**Comment by dhanushp** [comment]
![Poster](https://user-images.githubusercontent.com/43709470/107391719-fe071500-6b1e-11eb-90ee-491224067f4f.png)

Updated Poster. Do let me know if any changes are required.
