### ISSUE TITLE
Whorkshop Add-ons Mozilla

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/open-design#4]
Event Date: 27th April 2019
Event time: 1:00pm to 06:00pm
Event Name: Add-ons Mozilla
Event Venue: Ground floor Seminar Hall
Requirements:
1.Poster with event name, date,venue and time.
2.Certificate
3.An update about this event in new mozilla website
4.Logo for Mozilla Campus Club Sahyadri(as early as possible)

**Comment by nathanielmathew** [comment]
I'll handle the poster requirements for this workshop👍

**Comment by haxzie** [comment]
/remind @nathanielmathew to finish all the design works in 2 weeks
