### ISSUE TITLE
Kick Off CyberSec

### ISSUE THREAD

**Issue by akashdeepb** [so-sc/open-design#40]
## Event Description:
A Talk-ish on getting started with Cyber Security
https://github.com/so-sc/war-room/issues/29

#### Completion Date:
Check all that is applicable, add new ones if needed, remove the lines which aren't required.
- [ ] Poster (print)
- [X] Poster (Social Media)
- [X] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [ ] Invitation cards (Mention the details of invitation)
- [ ] Certificates (Mention the details below)
- [ ] Others (Specify the details below)
#### Details of the designs:
Something Attractive Hacky, Also a fancy name would be appreciated.

**Comment by dhanushp** [comment]
👍🏻

**Comment by dhanushp** [comment]
![Square](https://user-images.githubusercontent.com/43709470/124651381-7993a500-deb8-11eb-91fc-35c2ccab34ae.png)

**Comment by dhanushp** [comment]
![Web](https://user-images.githubusercontent.com/43709470/124651421-86b09400-deb8-11eb-8d77-61266a538df8.png)

**Comment by dhanushp** [comment]
![Square](https://user-images.githubusercontent.com/43709470/124740950-e058a300-df38-11eb-8daa-74946b286f44.png)

Updated poster @akashdeepb

**Comment by akashdeepb** [comment]
Thanks @dhanushp , Looks Amazing

**Comment by dhanushp** [comment]
![Square](https://user-images.githubusercontent.com/43709470/124953893-2a25b400-e033-11eb-8cca-2448b866f73c.png)


@akashdeepb Added timings
