### ISSUE TITLE
Fundamentals of Cloud Poster and Cerificate Design

### ISSUE THREAD

**Issue by akshayrb22** [so-sc/open-design#5]
## Event Description:
https://github.com/so-sc/war-room/issues/9
#### Completion Date: April 15th
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [x] Certificates (Mention the details below)
#### Details of the designs:
I was hoping to have a design ready for both the poster to be circulated on social media as well as a design for an e-certificate appreciating their participation. Any thoughts on this?

**Comment by haxzie** [comment]
@nathanielmathew @Dhanush-Bangera @jehadmohamedz @coderhawk999

**Comment by haxzie** [comment]
/remind @nathanielmathew to work on this designs in two weeks

**Comment by Dhanush-Bangera** [comment]
@nathanielmathew  Are you free to take this up?

**Comment by nathanielmathew** [comment]
@Dhanush-Bangera No, not until internals are finished, at least (17th April) 
Would you like to take it up?

**Comment by Dhanush-Bangera** [comment]
@nathanielmathew I'm currently working on Node School Workshop. We got time for this workshop, So will you be able to do it after your internals?

**Comment by nathanielmathew** [comment]
@Dhanush-Bangera sure

**Comment by nathanielmathew** [comment]
![Fundamentals of Cloud Computing](https://user-images.githubusercontent.com/22280173/56338847-6b6ae880-61c9-11e9-8b85-a8a7e2437f45.png)
![Fundamentals of Cloud Computing cover](https://user-images.githubusercontent.com/22280173/56338854-6e65d900-61c9-11e9-922c-d4f186ba8e00.png)

@akshayrb22 waiting for approval/necessary modifications

**Comment by akshayrb22** [comment]
Thanks, @nathanielmathew ! It looks great! But I was hoping I could have the DSC logo along with SOSC. Do you think we can add that? I'll email you the required assets.

**Comment by nathanielmathew** [comment]
Sure thing;
My email is nathanielmat2@gmail.com

**Comment by akshayrb22** [comment]
PFA the DSC Logo assets. Here is the link
<https://docs.google.com/document/d/1XnIMgA4MuCyx2P1f60xiqRZZNpcnCSMc2KSySUcabwQ/edit?usp=sharing>
to the branding guidelines. The guidelines apply to the new logo as well.
Regards,
Akshay

**Comment by haxzie** [comment]
Ladies and GentleMen,all the club logos are available in the same repo :)

**Comment by akshayrb22** [comment]
Actually, the logo was updated. I'm not sure if @coderhawk999 updated it in the repo.

**Comment by coderhawk999** [comment]
Ill update

**Comment by nathanielmathew** [comment]
will this do? @akshayrb22 
![Fundamentals of Cloud Computing](https://user-images.githubusercontent.com/22280173/56375445-25db0980-6223-11e9-8097-ba1ebc6f0b05.png)

**Comment by coderhawk999** [comment]
Can u make the color little more google ish???

**Comment by akshayrb22** [comment]
Now that you mention it @coderhawk999 , it does seem to lack the traditional Google colors. Maybe some green and red @nathanielmathew ?

**Comment by nathanielmathew** [comment]
@coderhawk999 @akshayrb22 
Well, this is currently the most of those colours I can add:
![Fundamentals of Cloud Computing Google Colours](https://user-images.githubusercontent.com/22280173/56376201-de557d00-6224-11e9-9257-3d3367853363.png)

**Comment by coderhawk999** [comment]
Mail the psd file to me.

**Comment by nathanielmathew** [comment]
It's a Canva Design @coderhawk999 
If you want to make edits:
Social Media Poster:
https://www.canva.com/design/DADXZ27wNnY/share/preview?token=Cj01VlYXonoQ2BbB2jAZyQ&role=EDITOR&utm_content=DADXZ27wNnY&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
Website Cover:
https://www.canva.com/design/DADXaBGgvgc/share/preview?token=JCrTYbtWDdjdXhA0XrRkUA&role=EDITOR&utm_content=DADXaBGgvgc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by nathanielmathew** [comment]
Also, for the certificates:
https://www.canva.com/design/DADUr4WYHvo/share/preview?token=kBNmpSNOmdYkuCqgsx41UA&role=EDITOR&utm_content=DADUr4WYHvo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by haxzie** [comment]
@nathanielmathew the certificate design can be improved.

**Comment by coderhawk999** [comment]
Variant-1
![fundamentals_of_cloud](https://user-images.githubusercontent.com/36099616/56512485-18df5280-6562-11e9-9234-2b575f25315f.jpg)
Variant-2
![fundamentals_of_cloud](https://user-images.githubusercontent.com/36099616/56512514-2bf22280-6562-11e9-9e3c-55f95ed1fde1.jpg)

**Comment by coderhawk999** [comment]
![fundamentals_of_cloud2](https://user-images.githubusercontent.com/36099616/56512756-e41fcb00-6562-11e9-8af4-2307aa741626.jpg)

**Comment by haxzie** [comment]
@coderhawk999 Check the SOSC logo, use the `logo_x_text` from this design repo for SOSC.
And is that the new Developer Students Club logo?

**Comment by coderhawk999** [comment]
Yeah its new logo of dsc 🙂
