### ISSUE TITLE
Node School Workshop

### ISSUE THREAD

**Issue by haxzie** [so-sc/open-design#6]
## Event Description:
https://github.com/so-sc/war-room/issues/10
#### Completion Date: 15/04/2019
Check all that is applicaple, add new ones if needed, remove the lines which aren't required.
- [X] Poster (print)
- [X] Poster (Social Media)
- [X] SOSC Website Event Cover
#### Details of the designs:
(Mention all the required details)

**Comment by Dhanush-Bangera** [comment]
Will start the work today 👍

**Comment by Dhanush-Bangera** [comment]
Poster done ✌️ 

![Poster](https://user-images.githubusercontent.com/43709470/56083017-84654980-5e17-11e9-8d9d-6d8d46be8671.png)

**Comment by haxzie** [comment]
Thank you @Dhanush-Bangera :+1:

**Comment by Dhanush-Bangera** [comment]
Instagram Story, I have left space for countdown timer on top 😄 Let me know if you want any changes

![Insta Story](https://user-images.githubusercontent.com/43709470/56343105-c4c71d80-61b1-11e9-800a-83b48e69ea20.png)

**Comment by haxzie** [comment]
This is awesome! Thanks @Dhanush-Bangera :heart:
