### ISSUE TITLE
Code _init_()

### ISSUE THREAD

**Issue by akashdeepb** [so-sc/open-design#7]
## Event Description:
https://github.com/so-sc/war-room/issues/13
#### Completion Date: 17/08/19
Check all that is applicaple, add new ones if needed, remove the lines which aren't required.
- [ ] Poster (print)
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [ ] Invitation cards (Mention the details of invitation)
- [ ] Certificates (Mention the details below)
- [ ] Others (Specify the details below)
#### Details of the designs:
Code _init_() will be name of the event, since it's focused more on people with 0 coding knowledge, try to make it appealing for these people.

**Comment by akashdeepb** [comment]
@so-sc/designteam please look after it

**Comment by nathanielmathew** [comment]
will do

**Comment by Dhanush-Bangera** [comment]
@nathanielmathew  You working on this?

**Comment by nathanielmathew** [comment]
> @nathanielmathew You working on this?

Yup

**Comment by nathanielmathew** [comment]
@akashdeepb event date and venue?

**Comment by akashdeepb** [comment]
@nathanielmathew 24/08/19 Ground Floor Seminar Hall at 1:30
