### ISSUE TITLE
Cloud Study Jam

### ISSUE THREAD

**Issue by akshayrb22** [so-sc/open-design#8]
## Event Description:
https://github.com/so-sc/war-room/issues/4
#### Completion Date: 03/08/2019
Check all that is applicable, add new ones if needed, remove the lines which aren't required.
- [x] Poster (print)
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [ ] Invitation cards (Mention the details of invitation)
- [ ] Certificates (Mention the details below)
- [ ] Others (Specify the details below)
#### Details of the designs:
(Mention all the required details)
This is an event that we want to make inclusive for all years, but we are focusing on the 2nd and 3rd years. If possible, try to make the design as beginner-friendly as possible. 

Edit: DSC has informed that each person to complete a Quest within 3 days of the course is eligible to receive swags from Google. Along with that, they have the opportunity to add the badge earned from the Quest directly to their LinkedIn accounts which is a major deal. 

Adding these details to the poster would benefit a great deal.

**Comment by akshayrb22** [comment]
@so-sc/designteam  Please take a look at it. Thanks! :smile:

**Comment by akshayrb22** [comment]
@so-sc/designteam  Any updates? I need to know if I can have it ready by 3rd. It would be great if someone could confirm their availability to complete this. Thanks. :smile:

**Comment by Dhanush-Bangera** [comment]
@nathanielmathew You taking this or should I?

**Comment by Dhanush-Bangera** [comment]
![Website Cover](https://user-images.githubusercontent.com/43709470/62106168-2a06d080-b2c2-11e9-9d1d-74af14dce8b9.png)

I have made the website cover. Let me know if you want any changes 😃

**Comment by Dhanush-Bangera** [comment]
![Website Cover](https://user-images.githubusercontent.com/43709470/62127464-bc719900-b2ef-11e9-9dcd-ff182b1a005d.png)

Updated one. Musthak approves 🤓

**Comment by akshayrb22** [comment]
Awesome! :smile:  Thanks @Dhanush-Bangera

**Comment by Dhanush-Bangera** [comment]
![Insta](https://user-images.githubusercontent.com/43709470/62132978-ab2e8980-b2fb-11e9-8a74-27f80139bd75.png)
For Instagram

**Comment by Dhanush-Bangera** [comment]
![Speaker](https://user-images.githubusercontent.com/43709470/62224415-44c96a00-b3d4-11e9-935e-e42076550508.png)

Speaker's post for Instagram. Do let me know before posting this. 😄

**Comment by Dhanush-Bangera** [comment]
Is there any more requirements? @akshayrb22

**Comment by akshayrb22** [comment]
No. This is perfect. Thanks a lot @Dhanush-Bangera. :+1:
