### ISSUE TITLE
Mozilla Design 101

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/open-design#9]
## Event Description:
_Design Workshop by Mozilla Open Design Domain. Adobe XD will be used to teach._  
[link to war room](https://github.com/so-sc/war-room/issues/14) 
#### Venue: 2nd floor seminar hall
Check all that is applicaple, add new ones if needed, remove the lines which aren't required.
- [x] Poster (print)
- [x] Poster (Social Media)
- [x] SOSC Website Event Cover
- [ ] Banner Outside Gate
- [ ] ID Cards (Mention what is required)
- [ ] Invitation cards (Mention the details of invitation)
- [ ] Certificates (Mention the details below)
- [ ] Others (Specify the details below)
#### Details of the designs:
(Creative poster. As we are having design workshop, the design of the poster itself should explain what they will get to learn. Please include "THE VERY FIRST DESIGN WORKSHOP IN SAHYADRI if possible.  )

**Comment by Dhanush-Bangera** [comment]
I will take this.

**Comment by Dhanush-Bangera** [comment]
![Web](https://user-images.githubusercontent.com/43709470/62561966-ddad2900-b89d-11e9-96e6-993064e523a9.png)

 SOSC Website Event Cover

**Comment by Dhanush-Bangera** [comment]
![Insta](https://user-images.githubusercontent.com/43709470/62562078-19e08980-b89e-11e9-8051-32edb7cacda5.png)

This is for Instagram and for circulating through WhatsApp .
This will be our first post in Instagram followed my speakers post (Below Pic).

![Speaker](https://user-images.githubusercontent.com/43709470/62562204-5613ea00-b89e-11e9-92e8-f8926338218f.png)

We have planned for some changes in Instagram. So please DM me before you post this in Instagram. 😄

**Comment by Basavarajeshwari-Ambi** [comment]
okay
